services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
      MYSQL_USER: sonn
      MYSQL_PASSWORD: 1111
    ports:
      - 3306:3306